"""
backend/orm/ai_opponent_argument.py
ORM model for storing AI-generated opponent arguments
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime, timezone

from backend.orm.base import Base


class AIOpponentArgument(Base):
    """
    Stores AI-generated opponent arguments for oral rounds.
    Tracks rebuttals generated by the AI opponent service.
    """
    __tablename__ = "ai_opponent_arguments"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Relationships
    round_id = Column(Integer, ForeignKey("oral_rounds.id"), nullable=False, index=True)
    generated_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    
    # Argument content
    user_argument_text = Column(Text, nullable=False)  # The argument being rebutted
    rebuttal_text = Column(Text, nullable=False)  # AI-generated rebuttal
    
    # AI-generated metadata (stored as JSON)
    legal_points = Column(JSON, default=list)  # List of legal points made
    suggested_cases = Column(JSON, default=list)  # Cases AI suggested to cite
    doctrine_applied = Column(String(255))  # e.g., "proportionality test"
    
    # Context information
    opponent_side = Column(String(20), nullable=False)  # "petitioner" or "respondent"
    moot_problem_context = Column(JSON, nullable=True)  # Snapshot of context used
    
    # Generation metadata
    generation_source = Column(String(20), default="llm")  # "llm" or "template"
    
    # Timestamps
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    # Relationships
    round = relationship("OralRound", back_populates="ai_arguments")
    generated_by = relationship("User", back_populates="ai_opponent_arguments")
    
    def __repr__(self):
        return f"<AIOpponentArgument(id={self.id}, round_id={self.round_id}, side={self.opponent_side})>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "round_id": self.round_id,
            "generated_by_user_id": self.generated_by_user_id,
            "user_argument_text": self.user_argument_text[:200] + "..." if len(self.user_argument_text) > 200 else self.user_argument_text,
            "rebuttal_text": self.rebuttal_text,
            "legal_points": self.legal_points or [],
            "suggested_cases": self.suggested_cases or [],
            "doctrine_applied": self.doctrine_applied,
            "opponent_side": self.opponent_side,
            "generation_source": self.generation_source,
            "created_at": self.created_at.isoformat() if self.created_at else None
        }
