"""Add is_active column to classroom_sessions

Revision ID: add_is_active_to_classroom_sessions
Revises: 
Create Date: 2025-02-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_active_to_classroom_sessions'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_sessions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_sessions', 'is_active')
    # ### end Alembic commands ###
